server:
  context-path: /mvc

logging:
  level:
    com.mvc.ethereum: DEBUG

org.ethereum:
#    address: http://192.168.206.229:8545
    address: http://127.0.0.1:8545

server:
  port: 8080

cors:
#  allowedOrigin: '*'
  allowedOrigin: '*'

swagger:
  enabled: false
  title: mvc-api-demo
  description: mvc-api-demo
  base-package:  com.mvc.ethereum.controller
  base-path: /**
  exclude-path: /error,/ops/**
  version: @project.version@

trans.log.url: http://rinkeby.etherscan.io/api